// Module API - Tous les appels API vers le serveur backend

// Import de la configuration (sera disponible via script tag dans le navigateur)
// const { CONFIG, getApiUrl } = require('./config.js');

// Fonction helper pour faire des requêtes avec gestion d'erreur
async function apiRequest(url, options = {}) {
  const response = await fetch(url, {
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });
  
  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(`API request failed: ${response.status} - ${errorText}`);
  }
  
  return response.json();
}

// Générer une playlist avec l'IA
async function generatePlaylist(selectedGenres, songCount, countryOrigin = null) {
  const url = `${CONFIG.API_BASE_URL}${CONFIG.ENDPOINTS.GENERATE_PLAYLIST}`;
  
  return apiRequest(url, {
    method: 'POST',
    body: JSON.stringify({
      selectedGenres,
      songCount,
      countryOrigin
    }),
    mode: 'cors',
    credentials: 'omit'
  });
}

// Obtenir l'URL d'authentification Spotify
async function getSpotifyAuthUrl() {
  const url = `${CONFIG.API_BASE_URL}${CONFIG.ENDPOINTS.SPOTIFY_AUTH}`;
  const response = await fetch(url);
  return response.json();
}

// Échanger le code d'authentification contre un token
async function exchangeCodeForToken(code) {
  const url = `${CONFIG.API_BASE_URL}${CONFIG.ENDPOINTS.SPOTIFY_TOKEN}`;
  
  return apiRequest(url, {
    method: 'POST',
    body: JSON.stringify({ code })
  });
}

// Rafraîchir un token Spotify expiré
async function refreshSpotifyToken(refreshToken) {
  const url = `${CONFIG.API_BASE_URL}${CONFIG.ENDPOINTS.REFRESH_SPOTIFY_TOKEN}`;
  
  return apiRequest(url, {
    method: 'POST',
    body: JSON.stringify({ refreshToken })
  });
}

// Créer une nouvelle playlist Spotify
async function createSpotifyPlaylistAPI(accessToken, playlistData, refreshToken = null) {
  const url = `${CONFIG.API_BASE_URL}${CONFIG.ENDPOINTS.CREATE_SPOTIFY_PLAYLIST}`;
  
  // Format data for Spotify
  const spotifyPlaylistData = {
    name: playlistData.playlist.name || 'AI Generated Playlist',
    description: playlistData.playlist.description || 'Generated by AI',
    songs: (playlistData.playlist.songs || []).map(song => ({
      title: song.title,
      artist: song.artist
    }))
  };
  
  try {
    let response = await fetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ 
        accessToken, 
        playlistData: spotifyPlaylistData 
      })
    });
    
    // If token expired, try to refresh it
    if (!response.ok && refreshToken) {
      try {
        const { accessToken: newAccessToken } = await refreshSpotifyToken(refreshToken);
        
        // Retry with new token
        response = await fetch(url, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ 
            accessToken: newAccessToken, 
            playlistData: spotifyPlaylistData 
          })
        });
      } catch (refreshError) {
        // Refresh failed, continue with original error
      }
    }
    
    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`Spotify creation failed: ${response.status} - ${errorText}`);
    }
    
    return response.json();
  } catch (error) {
    throw error;
  }
}

// Ajouter des chansons à une playlist Spotify existante
async function addSongsToSpotifyPlaylist(accessToken, playlistId, playlistData, refreshToken = null) {
  const url = `${CONFIG.API_BASE_URL}${CONFIG.ENDPOINTS.ADD_TO_SPOTIFY_PLAYLIST}`;
  
  // Format data for Spotify
  const spotifyPlaylistData = {
    name: playlistData.playlist.name || 'AI Generated Playlist',
    description: playlistData.playlist.description || 'Generated by AI',
    songs: (playlistData.playlist.songs || []).map(song => ({
      title: song.title,
      artist: song.artist
    }))
  };
  
  try {
    let response = await fetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ 
        accessToken, 
        playlistId,
        playlistData: spotifyPlaylistData 
      })
    });
    
    // If token expired, try to refresh it
    if (!response.ok && refreshToken) {
      try {
        const { accessToken: newAccessToken } = await refreshSpotifyToken(refreshToken);
        
        // Retry with new token
        response = await fetch(url, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ 
            accessToken: newAccessToken, 
            playlistId,
            playlistData: spotifyPlaylistData 
          })
        });
      } catch (refreshError) {
        // Refresh failed, continue with original error
      }
    }
    
    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`Spotify addition failed: ${response.status} - ${errorText}`);
    }
    
    return response.json();
  } catch (error) {
    throw error;
  }
}

// Exposer les fonctions globalement pour utilisation dans content.js
window.generatePlaylist = generatePlaylist;
window.getSpotifyAuthUrl = getSpotifyAuthUrl;
window.exchangeCodeForToken = exchangeCodeForToken;
window.refreshSpotifyToken = refreshSpotifyToken;
window.createSpotifyPlaylistAPI = createSpotifyPlaylistAPI;
window.addSongsToSpotifyPlaylist = addSongsToSpotifyPlaylist;

// Export pour utilisation dans d'autres modules (si Node.js)
if (typeof module !== 'undefined' && module.exports) {
  module.exports = {
    generatePlaylist,
    getSpotifyAuthUrl,
    exchangeCodeForToken,
    refreshSpotifyToken,
    createSpotifyPlaylist: createSpotifyPlaylistAPI,
    addSongsToSpotifyPlaylist
  };
}

