// Content-script bridge to Spotify operations in background.js (OAuth PKCE + Web API).

window.SPOTIFY_API_MODE = 'background';
window.SPOTIFY_API_BUILD = CONFIG.EXTENSION_VERSION;

function spotifyMessage(request) {
  return new Promise(function (resolve, reject) {
    if (typeof isExtensionContextValid === 'function' && !isExtensionContextValid()) {
      reject(new Error('Extension rechargée — actualisez la page Spotify (F5), puis réessayez.'));
      return;
    }

    chrome.runtime.sendMessage(request, function (response) {
      if (chrome.runtime.lastError) {
        reject(new Error(chrome.runtime.lastError.message || 'Spotify request failed'));
        return;
      }
      if (response && response.error) {
        reject(new Error(response.error));
        return;
      }
      resolve(response);
    });
  });
}

function mapSongs(playlistData) {
  const songs = (playlistData && playlistData.playlist && playlistData.playlist.songs) ||
    (playlistData && playlistData.songs) ||
    [];
  return songs.map(function (song) {
    return {
      title: song.title,
      artist: song.artist,
      spotifyUri: song.spotifyUri || null,
    };
  });
}

async function createSpotifyPlaylistAPI(_accessToken, playlistData, _refreshToken) {
  const playlist = (playlistData && playlistData.playlist) || playlistData || {};
  return spotifyMessage({
    type: 'createSpotifyPlaylist',
    playlistData: {
      name: playlist.name || 'AI Generated Playlist',
      description: playlist.description || 'Generated by AI',
      songs: mapSongs(playlistData),
    },
  });
}

async function addSongsToSpotifyPlaylist(_accessToken, playlistId, playlistData, _refreshToken) {
  return spotifyMessage({
    type: 'addSongsToPlaylist',
    playlistId: playlistId,
    songs: mapSongs(playlistData),
  });
}

window.createSpotifyPlaylistAPI = createSpotifyPlaylistAPI;
window.addSongsToSpotifyPlaylist = addSongsToSpotifyPlaylist;

if (typeof module !== 'undefined' && module.exports) {
  module.exports = {
    createSpotifyPlaylistAPI,
    addSongsToSpotifyPlaylist,
  };
}
